# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lgls.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(853, 551)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 531))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(650, 100, 151, 311))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.todaytasks = QtGui.QListWidget(self.tab)
        self.todaytasks.setGeometry(QtCore.QRect(480, 100, 151, 311))
        self.todaytasks.setObjectName(_fromUtf8("todaytasks"))
        self.deletetask = QtGui.QPushButton(self.tab)
        self.deletetask.setGeometry(QtCore.QRect(670, 460, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.deletetask.setFont(font)
        self.deletetask.setObjectName(_fromUtf8("deletetask"))
        self.dotoday = QtGui.QPushButton(self.tab)
        self.dotoday.setGeometry(QtCore.QRect(500, 440, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dotoday.setFont(font)
        self.dotoday.setObjectName(_fromUtf8("dotoday"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(480, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(650, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.addnewtaskbtn = QtGui.QPushButton(self.tab)
        self.addnewtaskbtn.setGeometry(QtCore.QRect(670, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.addnewtaskbtn.setFont(font)
        self.addnewtaskbtn.setObjectName(_fromUtf8("addnewtaskbtn"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(670, 60, 101, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 110, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.isurgent = QtGui.QCheckBox(self.groupBox_2)
        self.isurgent.setGeometry(QtCore.QRect(39, 26, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.isurgent.setFont(font)
        self.isurgent.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.isurgent.setObjectName(_fromUtf8("isurgent"))
        self.isimportant = QtGui.QCheckBox(self.groupBox_2)
        self.isimportant.setGeometry(QtCore.QRect(280, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.isimportant.setFont(font)
        self.isimportant.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.isimportant.setObjectName(_fromUtf8("isimportant"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 10, 431, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(260, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tasktitle = QtGui.QLineEdit(self.groupBox_3)
        self.tasktitle.setGeometry(QtCore.QRect(30, 40, 151, 31))
        self.tasktitle.setObjectName(_fromUtf8("tasktitle"))
        self.taskshortcut = QtGui.QLineEdit(self.groupBox_3)
        self.taskshortcut.setGeometry(QtCore.QRect(240, 40, 151, 31))
        self.taskshortcut.setObjectName(_fromUtf8("taskshortcut"))
        self.isextended_g = QtGui.QGroupBox(self.tab)
        self.isextended_g.setEnabled(True)
        self.isextended_g.setGeometry(QtCore.QRect(20, 230, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.isextended_g.setFont(font)
        self.isextended_g.setFlat(False)
        self.isextended_g.setCheckable(True)
        self.isextended_g.setObjectName(_fromUtf8("isextended_g"))
        self.label_5 = QtGui.QLabel(self.isextended_g)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.period = QtGui.QLineEdit(self.isextended_g)
        self.period.setGeometry(QtCore.QRect(120, 30, 101, 21))
        self.period.setObjectName(_fromUtf8("period"))
        self.label_7 = QtGui.QLabel(self.isextended_g)
        self.label_7.setGeometry(QtCore.QRect(250, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.endtime = QtGui.QTimeEdit(self.isextended_g)
        self.endtime.setGeometry(QtCore.QRect(327, 30, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.endtime.setFont(font)
        self.endtime.setObjectName(_fromUtf8("endtime"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 320, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.hardness = QtGui.QComboBox(self.groupBox)
        self.hardness.setGeometry(QtCore.QRect(190, 20, 121, 21))
        self.hardness.setObjectName(_fromUtf8("hardness"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(80, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 380, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tasknotes = QtGui.QPlainTextEdit(self.tab)
        self.tasknotes.setGeometry(QtCore.QRect(20, 400, 431, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tasknotes.setFont(font)
        self.tasknotes.setObjectName(_fromUtf8("tasknotes"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.starttime = QtGui.QTimeEdit(self.tab)
        self.starttime.setGeometry(QtCore.QRect(140, 190, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.starttime.setFont(font)
        self.starttime.setObjectName(_fromUtf8("starttime"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 771, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.groupBox_5 = QtGui.QGroupBox(self.widget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 100, 801, 391))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.listhours = QtGui.QListWidget(self.groupBox_5)
        self.listhours.setGeometry(QtCore.QRect(390, 30, 171, 351))
        self.listhours.setObjectName(_fromUtf8("listhours"))
        self.listhardness = QtGui.QListWidget(self.groupBox_5)
        self.listhardness.setGeometry(QtCore.QRect(680, 30, 41, 351))
        self.listhardness.setObjectName(_fromUtf8("listhardness"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 241, 351))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.super5 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.super5.setFont(font)
        self.super5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.super5.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SyrianArabRepublic))
        self.super5.setObjectName(_fromUtf8("super5"))
        self.verticalLayout.addWidget(self.super5)
        self.up4 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.up4.setFont(font)
        self.up4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.up4.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SyrianArabRepublic))
        self.up4.setObjectName(_fromUtf8("up4"))
        self.verticalLayout.addWidget(self.up4)
        self.medium3 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.medium3.setFont(font)
        self.medium3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.medium3.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SyrianArabRepublic))
        self.medium3.setObjectName(_fromUtf8("medium3"))
        self.verticalLayout.addWidget(self.medium3)
        self.down2 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.down2.setFont(font)
        self.down2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.down2.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SyrianArabRepublic))
        self.down2.setObjectName(_fromUtf8("down2"))
        self.verticalLayout.addWidget(self.down2)
        self.tired1 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.tired1.setFont(font)
        self.tired1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tired1.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SyrianArabRepublic))
        self.tired1.setObjectName(_fromUtf8("tired1"))
        self.verticalLayout.addWidget(self.tired1)
        self.asleep0 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.asleep0.setFont(font)
        self.asleep0.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.asleep0.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SyrianArabRepublic))
        self.asleep0.setObjectName(_fromUtf8("asleep0"))
        self.verticalLayout.addWidget(self.asleep0)
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableView = QtGui.QTableView(self.tab_2)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 801, 391))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.plan_the_day = QtGui.QPushButton(self.tab_2)
        self.plan_the_day.setGeometry(QtCore.QRect(30, 430, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.plan_the_day.setFont(font)
        self.plan_the_day.setObjectName(_fromUtf8("plan_the_day"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(640, 430, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.deletetask.setText(_translate("Dialog", "Finish Task", None))
        self.dotoday.setText(_translate("Dialog", "&Do Today", None))
        self.label.setText(_translate("Dialog", "Today Tasks", None))
        self.label_2.setText(_translate("Dialog", "Tasks Database", None))
        self.addnewtaskbtn.setText(_translate("Dialog", "Add New Task", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Type", None))
        self.isurgent.setText(_translate("Dialog", "Urgent", None))
        self.isimportant.setText(_translate("Dialog", "Important", None))
        self.label_3.setText(_translate("Dialog", "Task Title", None))
        self.label_4.setText(_translate("Dialog", "Task Shortcut", None))
        self.isextended_g.setTitle(_translate("Dialog", "isExtended", None))
        self.label_5.setText(_translate("Dialog", "Period (min) :", None))
        self.label_7.setText(_translate("Dialog", "End (Till):", None))
        self.groupBox.setTitle(_translate("Dialog", "hardness of Work", None))
        self.label_8.setText(_translate("Dialog", "hardness [1-5]", None))
        self.label_9.setText(_translate("Dialog", "Notes:", None))
        self.label_6.setText(_translate("Dialog", "Start Time:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tasks ", None))
        self.label_10.setText(_translate("Dialog", "Enter What you think is your productivity at this hours , only once for a lifetime [1-5] [0:sleep]", None))
        self.super5.setText(_translate("Dialog", "&5 - Super", None))
        self.up4.setText(_translate("Dialog", "&4 - Up", None))
        self.medium3.setText(_translate("Dialog", "&3 - Medium", None))
        self.down2.setText(_translate("Dialog", "&2 - Down", None))
        self.tired1.setText(_translate("Dialog", "&1 - Tired", None))
        self.asleep0.setText(_translate("Dialog", "&0 - Asleep", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Dialog", "Productivity", None))
        self.plan_the_day.setText(_translate("Dialog", "Schedule for Today and Lock", None))
        self.pushButton_11.setText(_translate("Dialog", "Print Preview", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Timesheet", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Feedback", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Progress and History", None))

